### ISSUE TITLE
[v1.4.0] Missing @media (Media Queries)

### ISSUE THREAD

**Issue by sectsect** [kimulaco/postcss-amp-custom#13]
**v.1.3.1** まではうまく残されていた`@media` (Media Queries)が**v1.4.0**ではRemoveされているようです。
ソースを見る限り、期待した挙動ではなさそうなので。

本件、コアの [amp-custom](https://github.com/kimulaco/amp-custom) の方で取り扱うべき問題かもしれませんが取り急ぎこちらで判断が難しいためこちらでチケット切らせていただきました。

たいへんお手数ですがご確認お願いします。

**Comment by kimulaco** [comment]
Issueの報告ありがとうございます。
私の手元では、次のように`@media`が残ることが確認できました。
他の削除ルールに巻き込まれて消えてしまっている可能性があるため、問題が発生しているリポジトリやサンプルコードを共有していただけますでしょうか。

**Input**

```css
@media screen and (min-width: 640px) {
  a {
    font-size: 18px;
    text-decoration: underline !important;
  }
}
```

**Output**

```css
@media screen and (min-width:640px){a{font-size:18px;text-decoration:underline}}
```
